### ISSUE TITLE
python 3.10 compatibility

### ISSUE THREAD

**Issue by tomaszputon** [googleapis/python-api-common-protos#109]
Hey,

is there anything that stops the library to be officially marked as Python 3.10 compatible? 🤔 `setup.py` is configured with all 3 py versions up to `"Programming Language :: Python :: 3.9"` - is it deliberate that python 3.10 is missing ? 

This package is reported as incompatible with Python 3.10 on this site https://pyreadiness.org/3.10/ that lists packages compatible with py3.10 based on `Programming Language :: Python :: 3.10` classifier.

Please update the classifiers if there's no issue with Python 3.10.

**Comment by vam-google** [comment]
I don't think it is deliberate, as most (all?) googleapis python repositories, including core ones are already python 3.10 compatible. 
We'll add 3.10 to this one as well, thanks for pointing it out.
