### ISSUE TITLE
Add type stub files to the Python package

### ISSUE THREAD

**Issue by jenstroeger** [googleapis/python-api-common-protos#134]
I wanted to replicate issue https://github.com/googleapis/google-cloud-python/issues/13361 here, because it looks like this repo is the correct place for it (in which case feel free to [transfer it](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository)).

**Comment by parthea** [comment]
Thanks for opening this feature request. I'm going to close this as a duplicate of https://github.com/googleapis/python-api-common-protos/issues/135
