### ISSUE TITLE
Remove dependency on pkg_resources

### ISSUE THREAD

**Issue by bivald** [googleapis/python-api-common-protos#140]
**Is your feature request related to a problem? Please describe.**
Trying to reduce boot time for my Cloud Run API I'm profiling imports, and google.rpc add significant time to the applications imports due to the use of pkg_resources

 **Describe the solution you'd like**
Similar to https://github.com/googleapis/python-api-core/pull/361 - it would be awesome if we could remove the use or pkg_resources (not idea of the effort though)

**Comment by jenshnielsen** [comment]
In addition to the above setuptools  has now deprecated the use of `pkg_resources.declare_namespace` 
which is still used in this package here https://github.com/googleapis/python-api-common-protos/blob/main/google/rpc/__init__.py and possibly elsewhere.

See the setuptools [changelog ](https://setuptools.pypa.io/en/latest/history.html#v67-3-0)

**Comment by meredithslota** [comment]
Dependent libraries still use https://github.com/googleapis/python-datastore/blob/main/google/__init__.py files — do these need to be removed manually?

**Comment by parthea** [comment]
Yes, it is necessary to remove `__init__.py` once we migrate to native namespace packages as per https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages. This work was already completed in `google-auth` via https://github.com/googleapis/google-auth-library-python/pull/1205. We will need to make a similar PR in each python repository in the `googleapis` organization.
