### ISSUE TITLE
Question: relationship between Common Protos and Protocol Buffers

### ISSUE THREAD

**Issue by jenstroeger** [googleapis/python-api-common-protos#169]
Hi, a question following up on [this discussion](https://groups.google.com/g/protobuf/c/Nq3km8llYbc) — how do the versions of this Python package relate to the upstream [Google APIs](https://github.com/googleapis/googleapis) and, more importantly, to the [Protocol Buffer releases](https://github.com/protocolbuffers/protobuf/releases)?

Or, to ask differently, which version of the [Python protobuf](https://github.com/protocolbuffers/protobuf/tree/v23.3/python) need I import in order to work safely with this Common package?

**Comment by vchudnov-g** [comment]
Hi Jens,

The `pb2` files used in this repo are generated by the `owlbot.py` file using `nox` [here](https://github.com/googleapis/python-api-common-protos/blob/394939a50496f068688c1b54bde1f66c1e40e68a/owlbot.py#L70). This file is used by the Owl-Bot bot to perform some repo post-processing in response to certain triggers. We have an [open issue](https://github.com/googleapis/python-api-common-protos/issues/3) to make the `pb2` files be generated via Bazel rules instead, which will make the process more regular and maintainable.

In terms of the versions of proto you can import: all the versions in [`setup.py`](https://github.com/googleapis/python-api-common-protos/blob/394939a50496f068688c1b54bde1f66c1e40e68a/setup.py#L26) will work. You can also see that in the [`testing/constraints-3.*.txt`](https://github.com/googleapis/python-api-common-protos/tree/main/testing)  files for various Python versions, we also test a range of `protobuf` versions (empty files/values mean to use the latest possible version).

Hope this helps!

**Comment by jenstroeger** [comment]
Thank you @vchudnov-g!
