### ISSUE TITLE
Update to the latest version of grpcio-tools

### ISSUE THREAD

**Issue by parthea** [googleapis/python-api-common-protos#94]
PR https://github.com/googleapis/python-api-common-protos/pull/87 regenerated pb2 files using the latest version of `grpcio-tools`. There is an issue reported in https://github.com/googleapis/python-api-common-protos/issues/91 where the changes result in `AttributeError: 'NoneType' object has no attribute 'message_types_by_name'`. I was able to reproduce the issue in a virtual environment using the steps in #91. The issue is no longer present when I pin `grpcio-tools<1.44.0` and regenerate protos using the previous version of `grpcio-tools`.

I've opened https://github.com/googleapis/python-api-common-protos/pull/93 to pin the version of `grpcio-tools` so development can continue in this repo.

**Comment by lidizheng** [comment]
A similar issue is reported at https://github.com/protocolbuffers/protobuf/issues/8803.

**Comment by lidizheng** [comment]
Can you try to bump the version of ProtoBuf and try again? For each gRPC release, we will try to use the ProtoBuf latest release at given time.

**Comment by parthea** [comment]
Thanks @lidizheng ! We'll bump the minimum protobuf to `3.15.0` here https://github.com/googleapis/python-api-common-protos/blob/main/setup.py#L25 . 

Version 3.15.0 doesn't have the error. In addition, the issue reported in #91 was using a pre-release version protobuf `4.0.0rc2` which is yanked. I tested the latest pre-release for `protobuf` version `protobuf-3.20.0rc2` and couldn't reproduce the issue.
